# Generated by Django 3.1.3 on 2022-03-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_auto_20201216_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='label_group',
        ),
        migrations.AddField(
            model_name='label',
            name='label_color',
            field=models.CharField(blank=True, choices=[('GREEN', 'Freshman'), ('YELLOW', 'Sophomore'), ('BLUE', 'Junior'), ('RED', 'Senior')], help_text='color of the labels shown when label is selected', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='order',
            field=models.IntegerField(default=0, help_text='sorting order of lables displayed on the tool (left-right, top-bottom) starts with 0'),
        ),
        migrations.AddField(
            model_name='label',
            name='parent_label',
            field=models.ForeignKey(blank=True, help_text='optional parameter to allow hierarchical labels', null=True, on_delete=django.db.models.deletion.CASCADE, to='labeling.label'),
        ),
    ]
