# Generated by Django 3.1.3 on 2022-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_auto_20220307_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='shortcut',
            field=models.CharField(blank=True, help_text='optional parameter for keyboard shortcut', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_color',
            field=models.CharField(blank=True, choices=[('#ff000063', 'RED'), ('#0091ff63', 'BLUE'), ('#5eff0063', 'GREEN'), ('#ebff0063', 'YELLOW'), ('#b000ff63', 'PURPLE'), ('#ffa00063', 'ORANGE'), ('#00ffff63', 'CYAN'), ('#a52a2a63', 'BROWN'), ('#00ff0063', 'LIME'), ('#80800063', 'OLIVE'), ('#00808063', 'TEAL'), ('#00ffff63', 'AQUA'), ('#f0ffff63', 'AZURE'), ('#ffe4c463', 'BISQUE'), ('#ff00ff63', 'FUCHSIA'), ('#d2691e63', 'CHOCOLATE'), ('#ff7f5063', 'CORAL'), ('#e9967a63', 'DARKSALMOn'), ('#8fbc8f63', 'DARKSEAGReen'), ('#ff149363', 'DEEPPINK'), ('#daa52063', 'GOLDENROD'), ('#adff2f63', 'GREENYELLOW')], help_text='color of the labels shown when label is selected', max_length=16, null=True),
        ),
    ]
