# Generated by Django 3.1.3 on 2020-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(help_text='name or reference to a label', max_length=255)),
                ('label_group', models.CharField(blank=True, help_text='additional parameter to group labels', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='url to original tweet', null=True)),
                ('full_text', models.TextField(help_text='text-content of the tweet')),
                ('labels_manual', models.TextField(blank=True, help_text='manually added labels', null=True)),
                ('labels_automatic', models.TextField(blank=True, help_text='calculated labels', null=True)),
                ('tweet_group', models.CharField(blank=True, help_text='additional parameter to group tweets', max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, help_text='keywords extracted from the tweet-text', null=True)),
                ('content', models.TextField(blank=True, help_text='full content of the tweet as json, provided by the api', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
